### ISSUE TITLE
fake implementation for unit tests

### ISSUE THREAD

**Issue by jack-evans** [IBM/cloudant-go-sdk#55]
**Is your feature request related to a problem? Please describe.**
When I use this sdk, it makes it difficult to unit test this without passing functions like `postDocument` in as a function argument and having to declare types in order to mock them in an easy way or I have to create a http test server and understand the underlying api calls that this cloudant SDK makes. I imagine other consumers of this library also hit the same problems.

**Describe the solution you'd like**
A fake implementation that allows a user to configure what a function call to cloudant returns. This allows users to maintain less code and have a single source of mocking calls to cloudant for unit testing.

**Describe alternatives you've considered**
As above in the first part.

**Additional context**

**Comment by eiri** [comment]
Right now we don't have plans to introduce lightweight test doubles for our sdk functions. We might look into it in the future, but it's not on a priority list.

What I can suggest is to define a service interface that'd specify a subset of `cloudant-go-sdk` functions your application's using, something like:

```go
type Service interface {
  PostDocument(opts *cloudantv1.PostDocumentOptions) (result *cloudantv1.DocumentResult, response *core.DetailedResponse, err error)
}
```

Then you can use it in your application instead of a direct instance of `CloudantV1` and mock it in your tests, so you wouldn't need to pass functions into them. This is pretty common approach in golang for testing a database layer in isolation and there are generic mocking libraries that simplify this, e.g. https://github.com/golang/mock, though they are adding a bit of a learning curve. 

Another approach would be more in an integration tests venue to run CouchDB or Cloudant docker container, a Cloudant service instance or a mock HTTP server and execute tests against them. We are using all three of those in our separate sdk's test suite and it proved to be reasonably reliable method.
